### ISSUE TITLE
Context not supported

### ISSUE THREAD

**Issue by daveneeley** [brandonaaron/livequery#6] opened 2010-09-17 14:44 UTC
In the following code, jquery should only select items that are children of #contextID.

```
    $("button, input:submit", "#contextID").livequery(function() {
        $(this).button();
    });
```

For some reason the context is being ignored by livequery. Everything works as expected if I change the code to

```
    $("#contextID button, #contextID input:submit").livequery(function() {
        $(this).button();
    });
```

**Comment by brandonaaron** [comment] 2014-04-10 12:55
Interesting. Looking back through the code, 4 years later, it does attempt to pass along the context to jQuery. Not sure what the issue is here. However, it is 4 years later and the plugin is finally getting some attention... but it is being rewritten to focus on the DOM mutations only and for modern browsers. I'm going to go ahead and close this issue out.

**Closed as completed by brandonaaron** 2014-04-10 12:55 UTC
